import numpy as np
import pandas as pd
from decimal import *
# Project Euler Problem 45

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

t = [0.5*n*(n+1) for n in range(285, 100000)]
p = [0.5*n*(3*n-1) for n in range(165, 100000)]
h = [n*(2*n-1) for n in range(143, 100000)]
y = [x for x in t if x in p if x in h]
print(y[1])