import numpy as np
import pandas as pd
from decimal import *
# Project Euler Problem 44

# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

n = [n*0.5*(3*n-1) for n in range(1,10000)]

c = [y-n[x] for x in range(len(n)) for y in n[x:] if y+n[x] in n if y-n[x] in n]
print(c)