import numpy as np
import pandas as pd

#Project Euler Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
arr = [1,2]
while arr[-1] < 4000000:
    arr.append(arr[-1]+arr[-2])
new = (x for x in arr if x%2 == 0)
print(sum(new))